apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stakater-front
  name: stakater-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stakater-front
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stakater-front
    spec:
      containers:
      - image: ps-container:dst
        name: ps-container
        resources: {}
status: {}
