apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: stakater-front
  name: stakater-front
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: stakater-front
  type: ClusterIP
status:
  loadBalancer: {}
